MatchMyPicsBundle\Entity\Indice:
    type: entity
    table: null
    repositoryClass: MatchMyPicsBundle\Repository\IndiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
    lifecycleCallbacks: {  }

    manyToOne:
        photo:
            targetEntity: MatchMyPicsBundle\Entity\Photo

        parametre:
            targetEntity: MatchMyPicsBundle\Entity\Parametre








