MatchMyPicsBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: MatchMyPicsBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        score:
            type: integer
    lifecycleCallbacks: {  }
