MatchMyPicsBundle\Entity\Team:
    type: entity
    table: fos_user
    repositoryClass: MatchMyPicsBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: UserAdmin
        score:
            type: integer
    lifecycleCallbacks: {  }

