fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Call routing admin
match_my_pics_admin:
    resource: "@MatchMyPicsBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

# Call routing user
match_my_pics_user:
    resource: "@MatchMyPicsBundle/Resources/config/routing_user.yml"
    prefix:   /


