MatchMyPicsBundle\Entity\Challenges:
    type: entity
    table: null
    repositoryClass: MatchMyPicsBundle\Repository\ChallengesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: '100'
            unique: true
        position:
            type: string
            length: 255
    lifecycleCallbacks: {  }
