MatchMyPicsBundle\Entity\Indices:
    type: entity
    table: null
    repositoryClass: MatchMyPicsBundle\Repository\IndicesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
    lifecycleCallbacks: {  }
