MatchMyPicsBundle\Entity\Parametres:
    type: entity
    table: null
    repositoryClass: MatchMyPicsBundle\Repository\ParametresRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        niveau:
            type: string
            length: '15'
        points:
            type: integer
    lifecycleCallbacks: {  }
