MatchMyPicsBundle\Entity\Solutions:
    type: entity
    table: null
    repositoryClass: MatchMyPicsBundle\Repository\SolutionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        photo:
            type: text
    lifecycleCallbacks: {  }
