# User
match_my_pics_index:
    path:     /
    defaults: { _controller: MatchMyPicsBundle:Default:index }

match_my_pics_rules:
    path:     /rules
    defaults: { _controller: MatchMyPicsBundle:Default:rules }

match_my_pics_home:
    path:     /{id}/home
    defaults: { _controller: MatchMyPicsBundle:Default:home }
    requirements:
        id: '\d+'

match_my_pics_challenges:
    path:     /{id}/challenges
    defaults: { _controller: MatchMyPicsBundle:Default:challenges }

match_my_pics_show_challenge:
    path:     /{id}/challenge_x
    defaults: { _controller: MatchMyPicsBundle:Default:showChallenge }
    requirements:
        id: '\d+'

match_my_pics_indice:
    path:     /{id}/indice
    defaults: { _controller: MatchMyPicsBundle:Default:indice }
    requirements:
        id: '\d+'

match_my_pics_redirection:
    path:     /redirect
    defaults: { _controller: MatchMyPicsBundle:Solution:redirect }

match_my_pics_abort:
    path:     /{id}/abort
    defaults: { _controller: MatchMyPicsBundle:Default:abort }
    requirements:
        id: '\d+'

solution_new:
    path:     /{id}/new
    defaults: { _controller: "MatchMyPicsBundle:Solution:new" }
    methods:  [GET, POST]
