# User
match_my_pics_solutions:
        resource: "@MatchMyPicsBundle/Resources/config/routing/solution.yml"
        prefix:   /solution

match_my_pics_challenge:
    resource: "@MatchMyPicsBundle/Resources/config/routing/challenge.yml"
    prefix:   /challenge

match_my_pics_index:
    path:     /
    defaults: { _controller: MatchMyPicsBundle:Default:index }

match_my_pics_rules:
    path:     /rules
    defaults: { _controller: MatchMyPicsBundle:Default:rules }

match_my_pics_home:
    path:     /home
    defaults: { _controller: MatchMyPicsBundle:Default:home }

match_my_pics_challenges:
    path:     /{id}/challenges
    defaults: { _controller: MatchMyPicsBundle:Default:challenges }

match_my_pics_show_challenge:
    path:     /{id}/challenge_x
    defaults: { _controller: MatchMyPicsBundle:Default:showChallenge }
    requirements:
        id: '\d+'

match_my_pics_indice:
    path:     /{id}/indice
    defaults: { _controller: MatchMyPicsBundle:Default:indice }
    requirements:
        id: '\d+'

# Admin

match_my_pics_sommaire_Admin:
    path:     /admin
    defaults: { _controller: MatchMyPicsBundle:Default:sommaireAdmin }

