<?php

namespace MatchMyPicsBundle\Repository;

/**
 * ChallengesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengesRepository extends \Doctrine\ORM\EntityRepository
{
}
