<?php

namespace MatchMyPicsBundle\Repository;

/**
 * IndicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicesRepository extends \Doctrine\ORM\EntityRepository
{
}
