<?php

namespace MatchMyPicsBundle\Repository;

/**
 * ParametresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreRepository extends \Doctrine\ORM\EntityRepository
{
}
