<?php

namespace MatchMyPicsBundle\Repository;

/**
 * PlayersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersRepository extends \Doctrine\ORM\EntityRepository
{
}
